name: dialogflow_flutter_plus_example
description: Demonstrates how to use the dialogflow_flutter_plus plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dialogflow_flutter_plus:
    path: ../

  cupertino_icons: ^1.0.2
  bubble: ^1.1.9+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
  - assets/
  - assets/farmtech-fh9j-3db6e0409c71.json

