name: dialogflow_flutter_plus
description: Plugin for using DialogFLow in flutter applications
version: 0.0.1
homepage: https://github.com/odejinmi/dialogflow_flutter_plus.git

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  googleapis_auth: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter




  